<a class="menu_block" href="<?php echo BASE_URL ?>admin/users/index.php">Учащиеся</a>
<a class="menu_block" href="<?php echo BASE_URL ?>admin/teachers/index.php">Преподаватели</a>
<a class="menu_block" href="<?php echo BASE_URL ?>admin/courses/index.php">Курсы</a>
<a class="menu_block" href="<?php echo BASE_URL ?>admin/groups/index.php">Группы</a>
<a class="menu_block" href="<?php echo BASE_URL ?>admin/lessons/index.php">Уроки</a>
<a class="menu_block" href="<?php echo BASE_URL ?>admin/timetable/index_this.php">Расписание</a>
<a class="menu_block" href="<?php echo BASE_URL ?>admin/visits/index.php">Посещения</a>
<a class="menu_block" href="<?php echo BASE_URL ?>admin/reports.php">Отчёты</a>
<a class="menu_block" href="<?php echo BASE_URL ?>admin/reference.php">Справка</a>
